l = log
lo = log --oneline
go = log --graph --oneline
goa = log --graph --all --oneline
lg = log --oneline --decorate --all --graph
ch = checkout
s = status
sw = switch
a = add
aa = add .
co = commit
ac = commit -a
coa = commit --amend
coan = commit --amend --no-edit
b = branch
dev = checkout develop
mas = checkout master
aliases = "!git config --get-regexp alias | sed 's/^alias\\.//'"
