# font size management 
map ctrl+shift+backspace change_font_size all 0

# splits management 
map ctrl+shift+enter launch --type=window --cwd=current
map ctrl+n launch
map ctrl+] next_window
map ctrl+[ previous_window

map ctrl+h neighboring_window left
map ctrl+j neighboring_window bottom
map ctrl+k neighboring_window top
map ctrl+l neighboring_window right

## Move splits
map ctrl+shift+alt+l move_window right
map ctrl+shift+alt+j move_window left
map ctrl+shift+alt+i move_window up
map ctrl+shift+alt+k move_window down

# tab management
map ctrl+shift+t new_tab
map ctrl+shift+w close_tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map ctrl+shift+h previous_tab
map ctrl+shift+l next_tab
