
# window management 
# map ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

# layout management
map ctrl+shift+l next_layout
map ctrl+alt+r goto_layout tall
map ctrl+alt+s goto_layout stack

# tab management
map ctrl+shift+t new_tab
# map ctrl+shift+right next_tab
# map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab



# Mappings
## Keybindings to move between splits
map ctrl+shift+up neighboring_window up
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+down neighboring_window down

## Split in the same directory
map ctrl+shift+enter launch --type=window --cwd=current

## Move splits
map ctrl+shift+alt+l move_window right
map ctrl+shift+alt+j move_window left
map ctrl+shift+alt+i move_window up
map ctrl+shift+alt+k move_window down